apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: pisharped
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  orders-service
  template:
    metadata:
      labels:
        app:  orders-service
    spec:
      containers:
      - name:  orders-service
        image: sanghvt/orders-service:main-46
        ports:
        - containerPort: 5000
